# GLONET Training Configuration
# ----------------------------- Configuration features
# config/                       
# ├── config.yaml               
# ├── model/                    
# │   ├── glonet.yaml           
# │   ├── glonet_patch.yaml
# │   └── glonet_cp.yaml   ✔   
# ├── data/                     
# │   └── GLORYS12.yaml    
# └── training/                 
#     ├── default.yaml
#     ├── fast.yaml   
#     └── optimic.yaml                   
          
# -----------------------------

checkpoint_paths: # Pre-trained model checkpoint paths. Need 3 parts for surface, shallow and deep ocean variables.
  part_1: "/Odyssey/public/glonet/TrainedWeights/glonet_part1.pth"
  part_2: "/Odyssey/public/glonet/TrainedWeights/glonet_part2.pth"
  part_3: "/Odyssey/public/glonet/TrainedWeights/glonet_part3.pth"

patch_size: ${computing.patch_size}