# Main GLONET Configuration
# ----------------------------- Configuration features
# config/                       
# ├── config.yaml               
# ├── model/                    
# │   ├── glonet.yaml           
# │   └── glonet_small.yaml     ✔
# ├── data/                     
# │   └── GLORYS12_0125.yaml    
# └── training/                 
#     ├── default.yaml          
#     └── fast.yaml              
# -----------------------------

# Lightweight GLONET Configuration for testing
_target_: src.glonetLit.Glonet

# Reduced model dimensions for faster testing
dim: [2, 5, 64, 64]  # Smaller spatial resolution

# Reduced architecture parameters  
dT: 32
dS: 32
NT: 1
NS: 4
ker: [3, 5]
groups: 4
