# GLONET Model Configuration
_target_: src.glonet.Glonet

# Model dimensions
dim: [2, 5, 128, 128]  # [T, C, H, W] - Time, Channels, Height, Width

# Architecture parameters
dT: 64              # Temporal dimension
dS: 64              # Spatial dimension  
NT: 2               # Number of temporal layers
NS: 8               # Number of spatial layers
ker: [3, 5, 7]      # Kernel sizes for inception blocks
groups: 8           # Number of groups for convolutions

# ============================================= Sub-module configurations ==
space:
  _target_: src.blocks.mspace
  channel_in: 5
  channel_hid: 64
  N_T: 2
  h: 128
  w: 128
  ker: [3, 5, 7, 11]
  groups: 8

dynamics:
  _target_: src.blocks.tmp
  dim: [2, 5, 128, 128]
  ni: 3
  n_heads: 8
  patch_size: [8, 8]

maps:
  _target_: src.NN.Encoder
  C_in: 5
  C_hid: 64
  N_S: 8

mapsback:
  _target_: src.NN.Decoder
  C_hid: 64
  C_out: 5
  N_S: 8