stages:
  - website

force-online-website-to-update:
  stage: website
  tags:
    - shell
  script:
    - make force-online-website-to-update
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "merge_request_event"
  retry:
    max: 2
