# Main GLONET Configuration
# ----------------------------- Configuration features
# config/                       
# ├── config.yaml          ✔     
# ├── model/                    
# │   ├── glonet.yaml           
# │   ├── glonet_patch.yaml
# │   └── glonet_cp.yaml      
# ├── data/                     
# │   └── GLORYS12.yaml    
# └── training/                 
#     ├── default.yaml
#     ├── fast.yaml   
#     └── optimic.yaml                   
          
# -----------------------------

defaults:
  - model: glonet_cp
  - data: GLORYS12_0125
  - training: optimic
  - _self_

# General settings
seed: 42

# Hydra settings
run_name: optimIC_GD
hydra:
  run:
    dir: ./outputs/${run_name}/${now:%Y-%m-%d-%H%M%S}
  job:
    name: ${run_name}