name: glonet_daily_forecast_data_orchestration
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1=py311h06a4308_0
  - xesmf=0.8.5=pyhd8ed1ab_0
  - netcdf4=1.6.5=nompi_py311he8ad708_100
  - xarray=2024.3.0=pyhd8ed1ab_0
  - copernicusmarine=1.3.4
  - pip:
      - zarr==2.17.2
      - numpy==1.24.4
      - torch==2.2.2
      - torchvision==0.17.2
      - Pillow==11.0.0
      - rioxarray==0.18.1
      - matplotlib==3.9.2
      - minio==7.2.11
