name: glonet_daily_forecast_data_orchestration
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - xesmf
  - netcdf4
  - xarray
  - copernicusmarine
  - zarr
  - numpy
  - pytorch
  - pytorch-cuda
  - torchvision
  - pillow
  - rioxarray
  - matplotlib
  - minio
  - cuda-toolkit
  - ipykernel