# Training Configuration
epochs: 100
batch_size: 4
learning_rate: 0.001
weight_decay: 1e-5

# Optimizer settings
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.learning_rate}
  weight_decay: ${training.weight_decay}
  betas: [0.9, 0.999]

# Scheduler settings
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${training.epochs}
  eta_min: 1e-6

# Loss function
loss:
  _target_: torch.nn.MSELoss

# Gradient clipping
grad_clip_norm: 1.0

# Mixed precision training
use_amp: false

# Early stopping
early_stopping:
  patience: 20
  min_delta: 1e-6
