# Lightning-specific training configuration
# Inherits from default.yaml with Lightning-specific additions

defaults:
  - default

# PyTorch Lightning specific settings
# Trainer settings
trainer:
  accelerator: "auto"
  devices: 1
  precision: 32
  deterministic: true


# Additional early stopping settings for Lightning
callbacks:
  checkpointing:
    monitor: "val_loss"
    save_top_k: 3
    mode: "min"
  early_stopping:
    monitor: "val_loss"
    min_delta: 0.0001
    patience: 15
    mode: "min"
