---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: glonet-daily-forecast-data-orchestration-cronjob
  namespace: project-glonet
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: glonet-daily-forecast-orchestration-cronjob
            image: docker.mercator-ocean.fr/moi-docker/glonet/glonet_daily_forecast_orchestration_cronjob:0.0.13
            imagePullPolicy: IfNotPresent
            env:
            - name: COPERNICUSMARINE_SERVICE_USERNAME
              value: $COPERNICUSMARINE_SERVICE_USERNAME
            - name: COPERNICUSMARINE_SERVICE_PASSWORD
              value: $COPERNICUSMARINE_SERVICE_PASSWORD
            - name: EDITO_OFFLINE_TOKEN
              value: $EDITO_OFFLINE_TOKEN
            - name: EDITO_MINIO_OFFLINE_TOKEN
              value: $EDITO_MINIO_OFFLINE_TOKEN
            resources:
              limits:
                memory: 128Mi
                cpu: 100m
              requests:
                memory: 128Mi
                cpu: 100m
          restartPolicy: OnFailure
