# Main GLONET Configuration
# ----------------------------- Configuration features
# config/                       
# ├── config.yaml               ✔
# ├── model/                    
# │   ├── glonet.yaml           
# │   └── glonet_small.yaml     
# ├── data/                     
# │   └── GLORYS12_0125.yaml    
# └── training/                 
#     ├── default.yaml          
#     └── fast.yaml             
# -----------------------------

defaults:
  - model: glonet
  - data: GLORYS12_0125
  - training: default
  - _self_

# General settings
seed: 42

# Hydra settings
run_name: debugrun
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${run_name}_${now:%H%M%S}
  job:
    name: ${run_name}