# Main GLONET Configuration
defaults:
  - model: glonet
  - training: default
  - data: default
  - _self_

# General settings
project_name: "glonet"
experiment_name: "test_run"
seed: 42
device: "cuda:0"

# Output settings
output_dir: "outputs"
save_checkpoint: true
checkpoint_interval: 10
log_interval: 100

# Hydra settings
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${experiment_name}-${now:%H-%M-%S}
  job:
    chdir: false
