name: glonet_daily_forecast_data_orchestration
channels:
  - conda-forge
  - pytorch
  - defaults
  - nvidia
dependencies:
  - pip
  - xesmf
  - netcdf4
  - xarray
  - copernicusmarine=2.1.3
  - zarr
  - numpy
  - pillow
  - rioxarray
  - matplotlib
  - minio
  - pytorch-cuda=12.4
  - cuda-toolkit=12.4.1
  - ipykernel
  - pip :
    - torch==2.7.1
    - torchvision==0.22.1
    - h5py